<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
<<<<<<< HEAD
  'rainlab\\blog\\Plugin' => 'plugins\\rainlab\\blog\\Plugin.php',
  'RainLab\\Blog\\Models\\Post' => 'plugins\\rainlab\\blog\\models\\Post.php',
  'RainLab\\Blog\\Classes\\TagProcessor' => 'plugins\\rainlab\\blog\\classes\\TagProcessor.php',
  'RainLab\\Blog\\Models\\Category' => 'plugins\\rainlab\\blog\\models\\Category.php',
  'rainlab\\pages\\Plugin' => 'plugins\\rainlab\\pages\\Plugin.php',
  'RainLab\\Blog\\Components\\Post' => 'plugins\\rainlab\\blog\\components\\Post.php',
  'RainLab\\Blog\\Components\\Posts' => 'plugins\\rainlab\\blog\\components\\Posts.php',
  'RainLab\\Blog\\Components\\Categories' => 'plugins\\rainlab\\blog\\components\\Categories.php',
  'RainLab\\Blog\\Components\\RssFeed' => 'plugins\\rainlab\\blog\\components\\RssFeed.php',
  'RainLab\\Pages\\Components\\ChildPages' => 'plugins\\rainlab\\pages\\components\\ChildPages.php',
  'RainLab\\Pages\\Components\\StaticPage' => 'plugins\\rainlab\\pages\\components\\StaticPage.php',
  'RainLab\\Pages\\Components\\StaticMenu' => 'plugins\\rainlab\\pages\\components\\StaticMenu.php',
  'RainLab\\Pages\\Components\\StaticBreadcrumbs' => 'plugins\\rainlab\\pages\\components\\StaticBreadcrumbs.php',
  'RainLab\\Pages\\Classes\\Snippet' => 'plugins\\rainlab\\pages\\classes\\Snippet.php',
  'RainLab\\Pages\\Classes\\Router' => 'plugins\\rainlab\\pages\\classes\\Router.php',
  'RainLab\\Pages\\Classes\\Page' => 'plugins\\rainlab\\pages\\classes\\Page.php',
  'RainLab\\Pages\\Classes\\SnippetManager' => 'plugins\\rainlab\\pages\\classes\\SnippetManager.php',
  'RainLab\\Pages\\Classes\\Controller' => 'plugins\\rainlab\\pages\\classes\\Controller.php',
  'RainLab\\Pages\\Classes\\PageList' => 'plugins\\rainlab\\pages\\classes\\PageList.php',
  'RainLab\\Pages\\Classes\\Menu' => 'plugins\\rainlab\\pages\\classes\\Menu.php',
  'backend\\Controllers\\media' => 'modules\\backend\\controllers\\media.php',
  'rainlab\\pages\\Controllers\\index' => 'plugins\\rainlab\\pages\\controllers\\index.php',
  'RainLab\\Pages\\Widgets\\PageList' => 'plugins\\rainlab\\pages\\widgets\\PageList.php',
  'RainLab\\Pages\\Widgets\\MenuList' => 'plugins\\rainlab\\pages\\widgets\\MenuList.php',
  'RainLab\\Pages\\Widgets\\TemplateList' => 'plugins\\rainlab\\pages\\widgets\\TemplateList.php',
  'RainLab\\Pages\\Widgets\\SnippetList' => 'plugins\\rainlab\\pages\\widgets\\SnippetList.php',
  'RainLab\\Pages\\Classes\\Content' => 'plugins\\rainlab\\pages\\classes\\Content.php',
  'RainLab\\Pages\\FormWidgets\\MenuItems' => 'plugins\\rainlab\\pages\\formwidgets\\MenuItems.php',
  'RainLab\\Pages\\Classes\\MenuItem' => 'plugins\\rainlab\\pages\\classes\\MenuItem.php',
  'Rainlab\\Pages\\FormWidgets\\MenuItemSearch' => 'plugins\\rainlab\\pages\\formwidgets\\MenuItemSearch.php',
  'RainLab\\Pages\\Classes\\MenuItemReference' => 'plugins\\rainlab\\pages\\classes\\MenuItemReference.php',
=======
  'peterhegman\\slickslider\\Plugin' => 'plugins\\peterhegman\\slickslider\\Plugin.php',
  'peterhegman\\slickslider\\Controllers\\slideshows' => 'plugins\\peterhegman\\slickslider\\controllers\\slideshows.php',
  'PeterHegman\\SlickSlider\\Models\\SlideShows' => 'plugins\\peterhegman\\slickslider\\models\\SlideShows.php',
>>>>>>> 3e0601e3633ed7eecf4909500e8566ad2ba1fda4
);